server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Luchn1k/microservice-config-store
          search-paths:
          - 'service-config/*service'
# private repo
#          username:
#          password:
