
security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      user-authorization-uri: http://localhost:8989/oauth/authorize
      access-token-uri: http://localhost:8989/oauth/token

    resource:
      token-info-uri: http://localhost:8989/oauth/check_token

server:
  servlet:
    session:
      cookie:
        name: KSESSION
  port: 8080